dual_motion_robot:
  #Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

 
  # Position Controllers ---------------------------------------
  chassis_pos_joint_controller:
    type: position_controllers/JointPositionController
    joint: chassis_pos_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
 
  #wheel_L_joint_joint_controller:
  #    type: effort_controllers/JointPositionController
  #    joint: wheel_L_joint
  #    pid: {p: 100.0, i: 0.01, d: 10.0}
      
      
  #wheel_R_joint_joint_controller:
  #    type: effort_controllers/JointPositionController
  #    joint: wheel_R_joint
  #    pid: {p: 100.0, i: 0.01, d: 10.0}  